package automation_script.Stride80.testmode;

import data_provider.testmode.DataProviderClassTestMode;
import org.testng.annotations.Test;
import page_objects.TestMode_Pages.NavigationPageTestMode;

import java.io.IOException;

public class TModeCombinedNoPresenceTestCase extends TestMode_BaseClass {

    @Test(dataProvider = "CombinedNoPresenceTestCaseData", dataProviderClass = DataProviderClassTestMode.class)
    public void validateCombinedNoPresenceTestCase(String disPlayMess, String soundMess, String noBatStatMessage, String stayFar,
                                                   String serialNumber, String keyPad, String proxyCard, String bioSensor, String osVersion) throws InterruptedException, IOException {

        new NavigationPageTestMode(driver)
                .navigateToDisplayTestPage()
                .ClickDisplayImage()
                .ClickDisplayImage()
                .ClickDisplayImage()
                .ClickDisplayImage()
                .validateDisplayMessage(disPlayMess)
                .ClickPassTest()
                .navigateToTouchTestPage()
                .ClickLeftCorner()
                .ClickRightCorner()
                .ClickBottomLeftCorner()
                .ClickBottomRightCorner()
                .navigateToSoundTestPage()
                .ClickToRecord()
                .ClickToStopRecord()
                .ClickToPlay()
                .ClickToStopPlay()
                .SoundTestMessageDisplayed()
                .validateSoundMessage(soundMess)
                .ClickToPass()
                .navigateToSpeakerTestPage()
                .clickToPlaySpeaker()
                .clickToPassSpeakerTest()
                .navigateToLightBarPage()
                .clickLightBarMode()
                .clickToOn()
                .clickLightBarColor()
                .clickToSelectAmber()
                .clickLightBarColor()
                .clickToSelectRed()
                .clickLightBarColor()
                .clickToSelectPurple()
                .clickLightBarColor()
                .clickToSelectWhite()
                .clickLightBarColor()
                .clickToSelectYellow()
                .selectLightBarBrightness()
                .selectBrightnessHundred()
                .selectLightBarBrightness()
                .selectBrightnessSixty()
                .selectLightBarBrightness()
                .selectBrightnessNinety()
                .selectLightBarBrightness()
                .selectBrightnessSeventy()
                .clickLightBarMode()
                .selectFlash()
                .clickLightBarMode()
                .selectOff()
                .selectPassTest()
                .navigateToPowerManagementPage()
                .verifyNoBatteryStatusMessage(noBatStatMessage)
                .selectPassTest()
                .navigateToRTCTestPage()
                .compareSysTimeVSRtcTime()
                .selectPassTest()
                .navigateToDiDoPage()
                .clickToChannelOneChkBox()
                .ClickToSetOutput()
                .ClickToReadOutputs()
                .ClickToReadInputs()
                .clickToChannelTwoChkBox()
                .ClickToSetOutput()
                .ClickToReadInputs()
                .clickToPassTest()
                .navigateToDiDoPage()
                .clickToChannelOneChkBox()
                .clickToChannelTwoChkBox()
                .ClickToSetOutput()
                .ClickToReadOutputs()
                .ClickToReadInputs()
                .clickToPassTest()
                .navigateToPresenceSensorTestPage()
                .verifyOutOfTheRange(stayFar)
                .navigateToAboutClockPage()
                .verifySerialNumber(serialNumber)
                .verifyKeypadAttached(keyPad)
                .verifyHidProxCard(proxyCard)
                .verifyBioSensor(bioSensor)
                .verifyOsVersion(osVersion)
                .clickToDone();

    }
}

